setwd("L:/BUT/SD/Promo 2025/mmounkailadjibo/Semestre 2/R/TD2/Dataset")
getwd()
donnee <- read.csv(file = "fao.csv" , sep = ";" , header = TRUE, dec = "," )
View(donnee)
dim(donnee)
nrow(donnee)
summary(donnee)
mean(donnee$Dispo_alim)
sum(donnee$Population, na.rm = TRUE )
moins = head(donnee[order(donnee$Population), ], 5)
View(moins)
